apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  selector:
    matchLabels:
      app: node-server
  replicas: 1
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: docker.io/abhays1/abhay:latest
        ports:
        - containerPort: 3000